<?php
/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

function renobestestate_preprocess_html(&$variables) {
  $node = \Drupal::request()->attributes->get('node');
  if (is_object($node)) {
    $variables['attributes']['class'][] = 'page-node-' . $node->id();
  }

  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $variables['language'] = $language;
}
